services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile

    environment:
      MONGO_DB_CONNECTION_URI: mongodb://${MONGO_USERNAME:?}:${MONGO_PASSWORD:?}@mongodb:27017/
      KAFKA_URL: ${KAFKA_URL:?} 

    container_name: main-app